### ISSUE TITLE
Missing source or target from Data Association edge in DI

### ISSUE THREAD

**Issue by aSegatto** [bpmn-miwg/bpmn-miwg-demos#44] opened 2017-03-15 12:17 UTC
Data association Edges should have source or target specified (as stated in 12.3.3), but in the reference BPMN the attribute is missing

**Comment by dgagne** [comment] 2017-03-15 15:20
Webmeeting 15 mar 2017
Issue was confirmed.

**Comment by falko** [comment] 2017-03-15 15:22
Which references are affected?

**Comment by aSegatto** [comment] 2017-03-15 15:46
The issue was raised against the file located at [this link](https://github.com/bpmn-miwg/bpmn-miwg-demos/blob/340340db56c4e74276985ca8cb85168316b9d964/2017-06-omg-technical-meeting-brussels/diagram-interchange-demo/Signal-Message-Datastore/Multi-diagram-All.bpmn)

**Comment by aSegatto** [comment] 2017-03-16 08:38
This are the references 
Reference: Bpmn_DataOutputAssociation_kbiUoAQqEeev4LOvjrydZw (in diagram "Onboarding employee")
Reference: _14e102e8-c9a3-4f05-b536-8c3ddd5a52f0 (in diagram "IT")
Reference: _40f59712-22d7-4a8a-8fdb-ef1461b2d8be (in diagram "IT")
Reference: _a7686b51-3e57-4c5c-bfd3-582d75e85ef2 (in diagram "IT")
Reference: Bpmn_DataInputAssociation_zKPS0AQsEeev4LOvjrydZw (in diagram "IT")
Reference: Bpmn_DataOutputAssociation_0F1_cgQsEeev4LOvjrydZw (in diagram "IT")
Reference: _0d4940de-b2cc-4216-8fd7-efc71ecebf80 (in diagram "Payroll")
Reference: Bpmn_DataOutputAssociation_iOm4IQQsEeev4LOvjrydZw (in diagram "Payroll")
Reference: Bpmn_DataInputAssociation_lqM1QgQsEeev4LOvjrydZw (in diagram "Payroll")
Reference: Bpmn_DataOutputAssociation_Rdj80QQsEeev4LOvjrydZw (in diagram "Facilities")
Reference: Bpmn_DataInputAssociation_SnKpMAQsEeev4LOvjrydZw (in diagram "Facilities")

**Comment by Francois-W4** [comment] 2017-03-21 09:13
As of now, we are not in a position to modify with our tool the data association edges issues;
Anyone in the group?

**Comment by bzinchenko** [comment] 2017-03-21 09:32
I see these in our log of import errors. We do not have an editor to correct these. I can try to fix by hand in XML, although it might be tricky.

**Comment by falko** [comment] 2022-02-19 13:20
Closing this because the 2017 demo has been successfully conducted and the resulting model became [reference C.4.0 in the test suite](https://github.com/bpmn-miwg/bpmn-miwg-test-suite/blob/master/Reference/C.4.0.bpmn).

**Closed by falko** 2022-02-19 13:20 UTC
