### ISSUE TITLE
Participant Label Shape

### ISSUE THREAD

**Issue by aSegatto** [bpmn-miwg/bpmn-miwg-demos#43] opened 2017-03-15 11:50 UTC
Hi, in the new multi diagram file, I've found that Participant labels do not have bounds. Although it is not required by specification this leads to some problems in our tool because we apply a default shape which causes the graphical outcome not to be so attractive. Is it possible to add a shape to this labels ?

**Comment by bzinchenko** [comment] 2017-03-15 12:00
@Alessandro, glory somebody noticed it! Is your issue the same as my issue described earlier in #41 ? Please give some more details. Are label boundaries really optional? If so, why our validation tools inspect them and detect as violations of compliance?

**Comment by aSegatto** [comment] 2017-03-15 12:32
This should be checked, but as far as I remember it's allowed not to specify label bounds , and in that case a default should be picked by the tool . My main concern was about the graphical outcome but maybe also correctness should be investigated. 
 In the issue you have raised, dimensions are set to 0 (#41) . Looks to me that in the last version of the model this is happening only on sequence flows labels which are empty. Maybe we should investigate this too as it may lead to problems in our tools

**Comment by bzinchenko** [comment] 2017-03-15 12:58
I ve just tested latest versions and nearly all label dimensions are still zero. There are few new elements added by another tool. They have normal dimensions and show up correctly.

**Comment by aSegatto** [comment] 2017-03-15 13:22
I found 41 label bounds with "0" width or height , and they all belong to a BPMNEdge label . Maybe your tool  sets dimensions to 0 when no label shape is specified ?

**Comment by bzinchenko** [comment] 2017-03-15 13:28
Awesome accuracy in counting missed dimensions! I have exactly same suspicion the reasons. What tool created this example? Maybe we should ask to fix this aspect? Maybe we can save samples in another tool, which provides correct label boundaries and re-upload?

**Comment by aSegatto** [comment] 2017-03-15 14:24
I agree it would be better to fix 0 bounds, maybe it can be done also from the tool that created the draft (I'm not sure what tool was used for labels ). I made a text search on the file to perform the count ! :smiley:

**Comment by dgagne** [comment] 2017-03-15 15:19
Webmeeting 15 Mar 2017
Issue was confirmed and assigned to Francois to modify accordingly

**Comment by Francois-W4** [comment] 2017-03-15 15:59
Zero label on sequence flows have been fixed.

Unfortunately our tool does not fix the participant label issue.

Who can take this point ?

**Comment by bzinchenko** [comment] 2017-03-15 16:34
Francois, thank you. I confirm that many labels have non-zero dimensions now. We can see some of them in our viewer now. However, many labels are still missing. We will research for the reasons. Maybe we will need also font adjustments to fit into given bounds with given font size.

**Comment by Francois-W4** [comment] 2017-03-15 16:54
Most of the links don't have any label. Do you mean labels are required on any object in your tool?

**Comment by bzinchenko** [comment] 2017-03-15 17:27
Good question! In fact, labels with valid boundaries exist for all objects in our reference models. All these models look fine when we open them in our viewer. I m not sure what standard says in this respect. If, by standard, labels are not obligatory, we should extend our rendering. However, I must stress that validator, which we use in BPMN MIWG for evaluation of new submissions normally shows label bounds for all objects.

**Comment by SimonRinguette** [comment] 2017-03-22 15:54
Resolved with the 22nd model

**Closed by SimonRinguette** 2017-03-22 15:54 UTC
